name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        context: ./mynodejs
        file: ./mynodejs/Dockerfile
    - name: login to docker
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PWD: ${{ secrets.DOCKER_PWD }} 

      run: docker login -u=$DOCKER_USER -p=$DOCKER_PWD 
    # Step 3: Build Docker image
    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./mynodejs  # Chemin vers le dossier contenant votre Dockerfile
        file: ./mynodejs/Dockerfile  # Chemin spécifique du Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USER }}/testnodeapp:latest
    # Step 4: Push Docker image to Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USER }}/testnodeapp:latest
