name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PWD: ${{ secrets.DOCKER_PWD }} 
    - uses: actions/checkout@v4
    - name: login to docker
      run: docker login --username=$DOCKER_USER --email=$DOCKER_PWD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USER/my-image-name:$(date +%s)
    - name: Push the Docker image
      run: docker push $DOCKER_USER/my-image-name:$(date +%s)
